// Code generated by go-bindata. DO NOT EDIT.
// sources:
// 201803042326_add_package.down.sql
// 201803042326_add_package.up.sql
package migrate

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var __201803042326_add_packageDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\x48\x28\x89\x2f\x2d\x4e\x2d\x4a\xb0\x06\x04\x00\x00\xff\xff\xa6\x15\x4f\x5c\x14\x00\x00\x00")

func _201803042326_add_packageDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__201803042326_add_packageDownSql,
		"201803042326_add_package.down.sql",
	)
}

func _201803042326_add_packageDownSql() (*asset, error) {
	bytes, err := _201803042326_add_packageDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "201803042326_add_package.down.sql", size: 20, mode: os.FileMode(420), modTime: time.Unix(1520230991, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __201803042326_add_packageUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x3c\x8d\xb1\x0e\x82\x30\x14\x45\x77\xbe\xe2\x8d\x6d\xe2\x40\x4c\x4c\x5c\x18\x0a\x3c\xb5\xb1\x14\x53\xcb\xc0\x44\x2b\x54\xed\x40\x4d\xb0\xfc\xbf\xa9\x26\xae\x37\xe7\xdc\x53\x29\x64\x1a\x41\xb3\x52\x20\x98\x38\xac\x6f\xb7\x18\x20\x19\x80\xf1\x93\x81\x9b\x7f\xf8\x10\xc9\x36\xa7\x20\x5b\x0d\xb2\x13\x02\x58\xa7\xdb\x81\xcb\x4a\x61\x83\x52\x6f\x12\x9a\xac\x21\xd8\xd9\x19\x18\x9f\x76\x21\xbb\x9c\x42\x8d\x07\xd6\x89\x9f\xf3\x85\xc6\xc5\xd9\xe8\x26\x03\x93\x8d\x2e\xfa\xd9\xa5\xf5\xa2\x78\xc3\x54\x0f\x67\xec\x81\xa4\x24\xcd\x28\xa0\x3c\x72\x89\x05\x0f\xe1\x55\x97\xff\xa3\xea\xc4\xd4\x15\x75\xb1\xc6\xfb\xfe\x13\x00\x00\xff\xff\xb5\x7c\xe3\x19\xb7\x00\x00\x00")

func _201803042326_add_packageUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__201803042326_add_packageUpSql,
		"201803042326_add_package.up.sql",
	)
}

func _201803042326_add_packageUpSql() (*asset, error) {
	bytes, err := _201803042326_add_packageUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "201803042326_add_package.up.sql", size: 183, mode: os.FileMode(420), modTime: time.Unix(1520231037, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"201803042326_add_package.down.sql": _201803042326_add_packageDownSql,
	"201803042326_add_package.up.sql":   _201803042326_add_packageUpSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"201803042326_add_package.down.sql": {_201803042326_add_packageDownSql, map[string]*bintree{}},
	"201803042326_add_package.up.sql":   {_201803042326_add_packageUpSql, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
